// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterUserReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=Code,proto3" json:"Code,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserReq) Reset()         { *m = RegisterUserReq{} }
func (m *RegisterUserReq) String() string { return proto.CompactTextString(m) }
func (*RegisterUserReq) ProtoMessage()    {}
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{0}
}

func (m *RegisterUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserReq.Unmarshal(m, b)
}
func (m *RegisterUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserReq.Marshal(b, m, deterministic)
}
func (m *RegisterUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserReq.Merge(m, src)
}
func (m *RegisterUserReq) XXX_Size() int {
	return xxx_messageInfo_RegisterUserReq.Size(m)
}
func (m *RegisterUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserReq proto.InternalMessageInfo

func (m *RegisterUserReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegisterUserReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *RegisterUserReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterUserReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RegisterUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterUserRsp struct {
	Status               *wrappers.BoolValue `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	UserID               int64               `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RegisterUserRsp) Reset()         { *m = RegisterUserRsp{} }
func (m *RegisterUserRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRsp) ProtoMessage()    {}
func (*RegisterUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{1}
}

func (m *RegisterUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRsp.Unmarshal(m, b)
}
func (m *RegisterUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRsp.Marshal(b, m, deterministic)
}
func (m *RegisterUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRsp.Merge(m, src)
}
func (m *RegisterUserRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRsp.Size(m)
}
func (m *RegisterUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRsp proto.InternalMessageInfo

func (m *RegisterUserRsp) GetStatus() *wrappers.BoolValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RegisterUserRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterUserRsp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type LoginPwdReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginPwdReq) Reset()         { *m = LoginPwdReq{} }
func (m *LoginPwdReq) String() string { return proto.CompactTextString(m) }
func (*LoginPwdReq) ProtoMessage()    {}
func (*LoginPwdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{2}
}

func (m *LoginPwdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPwdReq.Unmarshal(m, b)
}
func (m *LoginPwdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPwdReq.Marshal(b, m, deterministic)
}
func (m *LoginPwdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPwdReq.Merge(m, src)
}
func (m *LoginPwdReq) XXX_Size() int {
	return xxx_messageInfo_LoginPwdReq.Size(m)
}
func (m *LoginPwdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPwdReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPwdReq proto.InternalMessageInfo

func (m *LoginPwdReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginPwdReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginPhoneReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginPhoneReq) Reset()         { *m = LoginPhoneReq{} }
func (m *LoginPhoneReq) String() string { return proto.CompactTextString(m) }
func (*LoginPhoneReq) ProtoMessage()    {}
func (*LoginPhoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{3}
}

func (m *LoginPhoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginPhoneReq.Unmarshal(m, b)
}
func (m *LoginPhoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginPhoneReq.Marshal(b, m, deterministic)
}
func (m *LoginPhoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginPhoneReq.Merge(m, src)
}
func (m *LoginPhoneReq) XXX_Size() int {
	return xxx_messageInfo_LoginPhoneReq.Size(m)
}
func (m *LoginPhoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginPhoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginPhoneReq proto.InternalMessageInfo

func (m *LoginPhoneReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *LoginPhoneReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginRsp struct {
	Status               *wrappers.BoolValue `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Token                string              `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{4}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetStatus() *wrappers.BoolValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoginRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{5}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AuthReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SendMobileCodeReq struct {
	MobileNumber         string   `protobuf:"bytes,1,opt,name=MobileNumber,proto3" json:"MobileNumber,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMobileCodeReq) Reset()         { *m = SendMobileCodeReq{} }
func (m *SendMobileCodeReq) String() string { return proto.CompactTextString(m) }
func (*SendMobileCodeReq) ProtoMessage()    {}
func (*SendMobileCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{6}
}

func (m *SendMobileCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMobileCodeReq.Unmarshal(m, b)
}
func (m *SendMobileCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMobileCodeReq.Marshal(b, m, deterministic)
}
func (m *SendMobileCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMobileCodeReq.Merge(m, src)
}
func (m *SendMobileCodeReq) XXX_Size() int {
	return xxx_messageInfo_SendMobileCodeReq.Size(m)
}
func (m *SendMobileCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMobileCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMobileCodeReq proto.InternalMessageInfo

func (m *SendMobileCodeReq) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

func (m *SendMobileCodeReq) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type SendMobileCodeRsp struct {
	Status               *wrappers.BoolValue `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg                  string              `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SendMobileCodeRsp) Reset()         { *m = SendMobileCodeRsp{} }
func (m *SendMobileCodeRsp) String() string { return proto.CompactTextString(m) }
func (*SendMobileCodeRsp) ProtoMessage()    {}
func (*SendMobileCodeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33f3a5e1293a7bcd, []int{7}
}

func (m *SendMobileCodeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMobileCodeRsp.Unmarshal(m, b)
}
func (m *SendMobileCodeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMobileCodeRsp.Marshal(b, m, deterministic)
}
func (m *SendMobileCodeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMobileCodeRsp.Merge(m, src)
}
func (m *SendMobileCodeRsp) XXX_Size() int {
	return xxx_messageInfo_SendMobileCodeRsp.Size(m)
}
func (m *SendMobileCodeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMobileCodeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMobileCodeRsp proto.InternalMessageInfo

func (m *SendMobileCodeRsp) GetStatus() *wrappers.BoolValue {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SendMobileCodeRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUserReq)(nil), "user.proto.RegisterUserReq")
	proto.RegisterType((*RegisterUserRsp)(nil), "user.proto.RegisterUserRsp")
	proto.RegisterType((*LoginPwdReq)(nil), "user.proto.LoginPwdReq")
	proto.RegisterType((*LoginPhoneReq)(nil), "user.proto.LoginPhoneReq")
	proto.RegisterType((*LoginRsp)(nil), "user.proto.LoginRsp")
	proto.RegisterType((*AuthReq)(nil), "user.proto.AuthReq")
	proto.RegisterType((*SendMobileCodeReq)(nil), "user.proto.SendMobileCodeReq")
	proto.RegisterType((*SendMobileCodeRsp)(nil), "user.proto.SendMobileCodeRsp")
}

func init() { proto.RegisterFile("proto/message.proto", fileDescriptor_33f3a5e1293a7bcd) }

var fileDescriptor_33f3a5e1293a7bcd = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcb, 0x6b, 0xe3, 0x30,
	0x10, 0xc6, 0xb1, 0xf3, 0xd8, 0xec, 0x64, 0x9f, 0xda, 0xb0, 0x98, 0x1c, 0x96, 0x45, 0x87, 0x25,
	0x97, 0xd8, 0x90, 0x3d, 0x94, 0x1e, 0x9b, 0xb6, 0x94, 0x40, 0x13, 0x8c, 0xd3, 0x16, 0xda, 0x9b,
	0x1f, 0x13, 0xc7, 0xc4, 0xb6, 0x5c, 0xc9, 0x26, 0x7f, 0x46, 0xff, 0xe5, 0x22, 0xc9, 0x4e, 0xda,
	0xb4, 0x87, 0x1e, 0x72, 0xf2, 0x7c, 0x33, 0xd6, 0x8f, 0xef, 0x1b, 0x21, 0xf8, 0x55, 0x70, 0x56,
	0x32, 0x27, 0x43, 0x21, 0xfc, 0x18, 0x6d, 0xa5, 0x08, 0x54, 0x02, 0xb9, 0xae, 0x87, 0x7f, 0x62,
	0xc6, 0xe2, 0x14, 0x1d, 0xa5, 0x82, 0x6a, 0xe5, 0x6c, 0xb9, 0x5f, 0x14, 0xc8, 0x85, 0x9e, 0xd3,
	0x27, 0x03, 0xbe, 0x7b, 0x18, 0x27, 0xa2, 0x44, 0x7e, 0x2b, 0x90, 0x7b, 0xf8, 0x48, 0x86, 0xd0,
	0x93, 0xe5, 0xc2, 0xcf, 0xd0, 0x32, 0xfe, 0x1a, 0xa3, 0xcf, 0xde, 0x4e, 0xcb, 0xd9, 0x22, 0x09,
	0x37, 0x6a, 0x66, 0xea, 0x59, 0xa3, 0xc9, 0x00, 0x3a, 0xee, 0x9a, 0xe5, 0x68, 0xb5, 0xd4, 0x40,
	0x0b, 0x42, 0xa0, 0x7d, 0xce, 0x22, 0xb4, 0xda, 0xaa, 0xa9, 0x6a, 0x49, 0x71, 0x7d, 0x21, 0xb6,
	0x8c, 0x47, 0x56, 0x47, 0x53, 0x1a, 0x4d, 0xd9, 0x81, 0x21, 0x51, 0x90, 0x09, 0x74, 0x97, 0xa5,
	0x5f, 0x56, 0x42, 0xd9, 0xe9, 0x4f, 0x86, 0xb6, 0x4e, 0x65, 0x37, 0xa9, 0xec, 0x29, 0x63, 0xe9,
	0x9d, 0x9f, 0x56, 0xe8, 0xd5, 0x7f, 0x92, 0x1f, 0xd0, 0x9a, 0x8b, 0xb8, 0xf6, 0x28, 0x4b, 0xf2,
	0x1b, 0xba, 0x12, 0x38, 0xbb, 0x50, 0xfe, 0x5a, 0x5e, 0xad, 0xe8, 0x25, 0xf4, 0xaf, 0x59, 0x9c,
	0xe4, 0xee, 0x36, 0xfa, 0x40, 0xfa, 0x9d, 0x6f, 0xf3, 0xc0, 0xf7, 0x29, 0x7c, 0xd5, 0x18, 0x99,
	0x5a, 0x82, 0x76, 0xeb, 0x30, 0xde, 0x5b, 0x87, 0xb9, 0x5f, 0x07, 0x5d, 0x41, 0x4f, 0x1d, 0x3d,
	0x5e, 0xd6, 0x01, 0x74, 0x6e, 0xd8, 0x06, 0xf3, 0xe6, 0x2a, 0x94, 0xa0, 0x27, 0xf0, 0xe9, 0xac,
	0x2a, 0xd7, 0xd2, 0xdc, 0x7e, 0x19, 0xc6, 0xcb, 0x65, 0xc8, 0x83, 0x8a, 0x5d, 0xc3, 0xb4, 0xa0,
	0x57, 0xf0, 0x73, 0x89, 0x79, 0x34, 0x67, 0x41, 0x92, 0xa2, 0xb4, 0x2c, 0x11, 0x14, 0xbe, 0xe8,
	0xc6, 0xa2, 0xca, 0x02, 0xe4, 0x75, 0xcc, 0x57, 0x3d, 0xf2, 0x0d, 0xcc, 0x99, 0x5b, 0xb3, 0xcc,
	0x99, 0x4b, 0xef, 0xdf, 0x80, 0x8e, 0x15, 0x79, 0x3a, 0x7a, 0xf8, 0x17, 0x27, 0xe5, 0xba, 0x0a,
	0xec, 0x90, 0x65, 0x4e, 0x96, 0x84, 0x9c, 0x8d, 0x45, 0xe9, 0x87, 0x1b, 0xe1, 0xf0, 0x22, 0x1c,
	0xcb, 0x37, 0x51, 0xbf, 0x82, 0xae, 0xfa, 0xfc, 0x7f, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x43, 0x66,
	0x8c, 0x5c, 0x3d, 0x03, 0x00, 0x00,
}
